//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGH.GENERAL.Webparts.LGHCalendar {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class LGHCalendar {
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDate;
        
        public static implicit operator global::System.Web.UI.TemplateControl(LGHCalendar target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldivDate() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.divDate = @__ctrl;
            @__ctrl.ID = "divDate";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LGH.GENERAL.Webparts.LGHCalendar.LGHCalendar @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    $(document).ready(function () {\r\n\r" +
                        "\n        $(\".day_viw\").click(function () {\r\n            MoveView(\'day\');\r\n      " +
                        "  });\r\n\r\n        $(\".week_viw\").click(function () {\r\n            MoveView(\'week\'" +
                        ");\r\n        });\r\n\r\n        $(\".month_viw\").click(function () {\r\n            Move" +
                        "View(\'month\')\r\n        });\r\n\r\n        $(\"body\").on(\"mousedown mouseup dblclick m" +
                        "ousemove\", \".ms-acal-rootdiv td\", false);\r\n    });\r\n\r\n    _spOriginalFormAction " +
                        "= document.forms[0].action;\r\n    _spSuppressFormOnSubmitWrapper = true;\r\n\r\n    /" +
                        "/$(document).ready(function () { $(\'.ms-cal-dayitem\').each(function () { $(this)" +
                        ".removeAttr(\'href\'); $(this).removeAttr(\'onclick\'); $(this).closest(\"td\").remove" +
                        "Attr(\'href\'); $(this).closest(\"td\").removeAttr(\'onclick\'); }); $(\'.ms-cal-defaul" +
                        "tbgcolor\').each(function () { $(this).removeAttr(\'href\'); $(this).removeAttr(\'on" +
                        "click\'); $(this).children(\"a\").removeAttr(\'href\'); $(this).children(\"a\").removeA" +
                        "ttr(\'onclick\'); }); });\r\n\r\n\r\n    //$(\".ms-acal-rootdiv\").bind(\"click dblclick\", " +
                        "function () {\r\n    //    return false;\r\n    //});\r\n\r\n    //setInterval(function " +
                        "() {\r\n    //    $(\".ms-acal-item [bricked!=\'1\']\").each(function () {\r\n    //    " +
                        "    $(this).attr(\"bricked\", \"1\").bind(\"click dblclick\", function () {\r\n    //   " +
                        "         return false;\r\n    //        });\r\n    //    });\r\n    //    // Single da" +
                        "y events\r\n    //    $(\".ms-acal-sdiv a\").each(function () {\r\n    //        var t" +
                        "ext = $(this).text();\r\n    //        $(this).before(text);\r\n    //        $(this" +
                        ").remove();\r\n\r\n    //    });\r\n    //    // Events spanning multiple days\r\n    //" +
                        "    $(\".ms-acal-mdiv a\").each(function () {\r\n    //        var text = $(this).te" +
                        "xt();\r\n    //        $(this).before(text);\r\n    //        $(this).remove();\r\n\r\n " +
                        "   //    });\r\n\r\n    //}, 500);\r\n\r\n\r\n\r\n    //var tables = document.getElementsByT" +
                        "agName(\"TABLE\");\r\n    //for (var i = 0; i < tables.length; i++) {\r\n\r\n    //    i" +
                        "f (tables[i].summary == \"Monthly graphical Calendar View\") {\r\n\r\n    //        va" +
                        "r TDs = tables[i].getElementsByTagName(\"TD\");\r\n    //        for (var j = 0; j <" +
                        " TDs.length; j++) {\r\n\r\n    //            if (TDs[j].className == \"ms-cal-monthit" +
                        "em\") {\r\n    //                var As = TDs[j].getElementsByTagName(\"A\");\r\n    //" +
                        "                if (As.length > 0) {\r\n    //                    TDs[j].innerText" +
                        " = As[0].innerText;\r\n    //                }\r\n    //            }\r\n    //       " +
                        " }\r\n    //        break;\r\n    //    }\r\n    //}\r\n\r\n    //ExecuteOrDelayUntilScrip" +
                        "tLoaded(function () {\r\n\r\n    //    //Disable calendar events\r\n    //    $(\'.ms-a" +
                        "cal-rootdiv td\').on(\"mousedown mouseup dblclick mousemove\", false);\r\n\r\n    //}, " +
                        "\'SP.UI.ApplicationPages.Calendar.js\');\r\n\r\n\r\n\r\n    // load our function to the de" +
                        "layed load list\r\n    ////_spBodyOnLoadFunctionNames.push(\'hideCalendarEventLinkI" +
                        "ntercept\');\r\n\r\n    ////// hook into the existing SharePoint calendar load functi" +
                        "on\r\n    ////function hideCalendarEventLinkIntercept() {\r\n    ////    var OldCale" +
                        "ndarNotify4a = SP.UI.ApplicationPages.CalendarNotify.$4b;\r\n    ////    SP.UI.App" +
                        "licationPages.CalendarNotify.$4b = function () {\r\n    ////        OldCalendarNot" +
                        "ify4a();\r\n    ////        hideCalendarEventLinks();\r\n    ////    }\r\n    ////}\r\n\r" +
                        "\n    ////// hide the hyperlinks\r\n    ////function hideCalendarEventLinks() {\r\n\r\n" +
                        "    ////    // find all DIVs\r\n    ////    var divs = document.getElementsByTagNa" +
                        "me(\"DIV\");\r\n    ////    for (var i = 0; i < divs.length; i++) {\r\n    ////       " +
                        " // find calendar item DIVs\r\n    ////        if (divs[i].className.toLowerCase()" +
                        " == \"ms-acal-item\") {\r\n    ////            // find the hyperlink\r\n    ////      " +
                        "      var links = divs[i].getElementsByTagName(\"A\");\r\n    ////            if (li" +
                        "nks.length == 1) {\r\n    ////                // replace the hyperlink with text\r\n" +
                        "    ////                links[0].parentNode.innerHTML = links[0].innerHTML\r\n    " +
                        "////            }\r\n    ////        }\r\n\r\n    ////        // find \"x more items\" l" +
                        "inks and re-remove links on Expand/Contract\r\n    ////        if (divs[i].classNa" +
                        "me.toLowerCase() == \"ms-acal-ctrlitem\") {\r\n    ////            var links = divs[" +
                        "i].getElementsByTagName(\"A\");\r\n    ////            if (links.length == 1) {\r\n   " +
                        " ////                links[0].href = \"javascript:hideCalendarEventLinks();void(0" +
                        ");\"\r\n    ////            }\r\n    ////        }\r\n\r\n    ////    }\r\n    ////}\r\n\r\n\r\n<" +
                        "/script>\r\n\r\n<style type=\"text/css\">\r\n    /*.ms-acal-rootdiv A[title=\"Add\"] {\r\n  " +
                        "      display: none;\r\n    }*/\r\n    table.ms-acal-vcont tbody tr td a {display:no" +
                        "ne !important;}\r\n</style>\r\n\r\n<div>\r\n    \r\n            <div class=\"cal_sidebar\">\r" +
                        "\n\t\t\t    \r\n\t\t\t    <div class=\"cal_view\">\r\n                    <ul class=\"cal_ico\"" +
                        ">\r\n\t\t\t\t\t\t<li><span class=\"day_viw\">Day</span></li>\r\n\t\t\t\t\t\t<li><span class=\"week_" +
                        "viw\">Week</span></li>\r\n\t\t\t\t\t\t<li><span class=\"month_viw\">Month</span></li>\r\n\t\t\t\t" +
                        "\t</ul>\r\n\t\t        </div>\r\n                <div id=\"DatePickerDiv\" style=\"display" +
                        ":block  \">\r\n                    <div class=\"ms-datepickerouter\"> \r\n             " +
                        "           <div class=\"ms-quickLaunch\">\r\n                            <div class=" +
                        "\"ms-picker-header\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"ms-p" +
                        "icker-table\"><tbody><tr> <td align=\"center\"><a href=\"javascript:MoveToDate(\'12\\u" +
                        "002f18\\u002f2013\');\" accesskey=\"<\" title=\"Previous Year 2013\" class=\"ms-pagearro" +
                        "w-left\"><img border=\"0\" alt=\"Previous Year 2013\" src=\"/_layouts/15/images/spcomm" +
                        "on.png?rev=23\" class=\"ms-pagearrow-left-icon\"></a></td>\r\n                       " +
                        "         <td class=\"ms-picker-month\" nowrap=\"nowrap\" align=\"center\">&nbsp;2014&n" +
                        "bsp;</td>\r\n                                <td align=\"center\"><a href=\"javascrip" +
                        "t:MoveToDate(\'12\\u002f18\\u002f2015\');\" accesskey=\">\" title=\"Next Year 2015\" clas" +
                        "s=\"ms-pagearrow-right\"><img border=\"0\" alt=\"Next Year 2015\" src=\"/_layouts/15/im" +
                        "ages/spcommon.png?rev=23\" class=\"ms-pagearrow-right-icon\"></a></td>\r\n           " +
                        "                     </tr></tbody></table>\r\n                            </div>\r\n" +
                        "                            <div class=\"ms-picker-body\"><table cellpadding=\"0\" c" +
                        "ellspacing=\"0\" border=\"0\" class=\"ms-picker-table\">\r\n                            " +
                        "    <tbody><tr><td colspan=\"3\" class=\"ms-picker-line\"></td></tr>\r\n              " +
                        "                  <tr>\r\n                                <td class=\"ms-picker-mon" +
                        "thcenter\" onmouseover=\"this.className=\'ms-picker-monthcenterOn\';\" onmouseout=\"th" +
                        "is.className=\'ms-picker-monthcenter\';\" onclick=\"javascript:ClickDay(\'1\\u002f18\\u" +
                        "002f2014\')\" \"january\"=\"\"><a href=\"javascript:ClickDay(\'1\\u002f18\\u002f2014\')\" id" +
                        "=\"20140118\"><span class=\"ms-accessible\"></span>Jan<span class=\"ms-accessible\">20" +
                        "14</span></a></td>\r\n                                <td class=\"ms-picker-monthce" +
                        "nter\" onmouseover=\"this.className=\'ms-picker-monthcenterOn\';\" onmouseout=\"this.c" +
                        "lassName=\'ms-picker-monthcenter\';\" onclick=\"javascript:ClickDay(\'2\\u002f18\\u002f" +
                        "2014\')\" \"february\"=\"\"><a href=\"javascript:ClickDay(\'2\\u002f18\\u002f2014\')\" id=\"2" +
                        "0140218\"><span class=\"ms-accessible\"></span>Feb<span class=\"ms-accessible\">2014<" +
                        "/span></a></td>\r\n                                <td class=\"ms-picker-monthcente" +
                        "r\" onmouseover=\"this.className=\'ms-picker-monthcenterOn\';\" onmouseout=\"this.clas" +
                        "sName=\'ms-picker-monthcenter\';\" onclick=\"javascript:ClickDay(\'3\\u002f18\\u002f201" +
                        "4\')\" \"march\"=\"\"><a href=\"javascript:ClickDay(\'3\\u002f18\\u002f2014\')\" id=\"2014031" +
                        "8\"><span class=\"ms-accessible\"></span>Mar<span class=\"ms-accessible\">2014</span>" +
                        "</a></td>\r\n                                </tr>\r\n                              " +
                        "  <tr>\r\n                                <td class=\"ms-picker-monthcenter\" onmous" +
                        "eover=\"this.className=\'ms-picker-monthcenterOn\';\" onmouseout=\"this.className=\'ms" +
                        "-picker-monthcenter\';\" onclick=\"javascript:ClickDay(\'4\\u002f18\\u002f2014\')\" \"apr" +
                        "il\"=\"\"><a href=\"javascript:ClickDay(\'4\\u002f18\\u002f2014\')\" id=\"20140418\"><span " +
                        "class=\"ms-accessible\"></span>Apr<span class=\"ms-accessible\">2014</span></a></td>" +
                        "\r\n                                <td class=\"ms-picker-monthcenter\" onmouseover=" +
                        "\"this.className=\'ms-picker-monthcenterOn\';\" onmouseout=\"this.className=\'ms-picke" +
                        "r-monthcenter\';\" onclick=\"javascript:ClickDay(\'5\\u002f18\\u002f2014\')\" \"may\"=\"\"><" +
                        "a href=\"javascript:ClickDay(\'5\\u002f18\\u002f2014\')\" id=\"20140518\"><span class=\"m" +
                        "s-accessible\"></span>May<span class=\"ms-accessible\">2014</span></a></td>\r\n      " +
                        "                          <td class=\"ms-picker-monthcenter\" onmouseover=\"this.cl" +
                        "assName=\'ms-picker-monthcenterOn\';\" onmouseout=\"this.className=\'ms-picker-monthc" +
                        "enter\';\" onclick=\"javascript:ClickDay(\'6\\u002f18\\u002f2014\')\" \"june\"=\"\"><a href=" +
                        "\"javascript:ClickDay(\'6\\u002f18\\u002f2014\')\" id=\"20140618\"><span class=\"ms-acces" +
                        "sible\"></span>Jun<span class=\"ms-accessible\">2014</span></a></td>\r\n             " +
                        "                   </tr>\r\n                                <tr>\r\n                " +
                        "                <td class=\"ms-picker-monthcenter\" onmouseover=\"this.className=\'m" +
                        "s-picker-monthcenterOn\';\" onmouseout=\"this.className=\'ms-picker-monthcenter\';\" o" +
                        "nclick=\"javascript:ClickDay(\'7\\u002f18\\u002f2014\')\" \"july\"=\"\"><a href=\"javascrip" +
                        "t:ClickDay(\'7\\u002f18\\u002f2014\')\" id=\"20140718\"><span class=\"ms-accessible\"></s" +
                        "pan>Jul<span class=\"ms-accessible\">2014</span></a></td>\r\n                       " +
                        "         <td class=\"ms-picker-monthcenter\" onmouseover=\"this.className=\'ms-picke" +
                        "r-monthcenterOn\';\" onmouseout=\"this.className=\'ms-picker-monthcenter\';\" onclick=" +
                        "\"javascript:ClickDay(\'8\\u002f18\\u002f2014\')\" \"august\"=\"\"><a href=\"javascript:Cli" +
                        "ckDay(\'8\\u002f18\\u002f2014\')\" id=\"20140818\"><span class=\"ms-accessible\"></span>A" +
                        "ug<span class=\"ms-accessible\">2014</span></a></td>\r\n                            " +
                        "    <td class=\"ms-picker-monthcenter\" onmouseover=\"this.className=\'ms-picker-mon" +
                        "thcenterOn\';\" onmouseout=\"this.className=\'ms-picker-monthcenter\';\" onclick=\"java" +
                        "script:ClickDay(\'9\\u002f18\\u002f2014\')\" \"september\"=\"\"><a href=\"javascript:Click" +
                        "Day(\'9\\u002f18\\u002f2014\')\" id=\"20140918\"><span class=\"ms-accessible\"></span>Sep" +
                        "<span class=\"ms-accessible\">2014</span></a></td>\r\n                              " +
                        "  </tr>\r\n                                <tr>\r\n                                <" +
                        "td class=\"ms-picker-monthcenter\" onmouseover=\"this.className=\'ms-picker-monthcen" +
                        "terOn\';\" onmouseout=\"this.className=\'ms-picker-monthcenter\';\" onclick=\"javascrip" +
                        "t:ClickDay(\'10\\u002f18\\u002f2014\')\" \"october\"=\"\"><a href=\"javascript:ClickDay(\'1" +
                        "0\\u002f18\\u002f2014\')\" id=\"20141018\"><span class=\"ms-accessible\"></span>Oct<span" +
                        " class=\"ms-accessible\">2014</span></a></td>\r\n                                <td" +
                        " class=\"ms-picker-monthcenter\" onmouseover=\"this.className=\'ms-picker-monthcente" +
                        "rOn\';\" onmouseout=\"this.className=\'ms-picker-monthcenter\';\" onclick=\"javascript:" +
                        "ClickDay(\'11\\u002f18\\u002f2014\')\" \"november\"=\"\"><a href=\"javascript:ClickDay(\'11" +
                        "\\u002f18\\u002f2014\')\" id=\"20141118\"><span class=\"ms-accessible\"></span>Nov<span " +
                        "class=\"ms-accessible\">2014</span></a></td>\r\n                                <td " +
                        "class=\"ms-picker-monthselected\" onmouseover=\"this.className=\'ms-picker-monthsele" +
                        "cted\';\" onmouseout=\"this.className=\'ms-picker-monthselected\';\" onclick=\"javascri" +
                        "pt:ClickDay(\'12\\u002f18\\u002f2014\')\" \"december\"=\"\"><a href=\"javascript:ClickDay(" +
                        "\'12\\u002f18\\u002f2014\')\" id=\"20141218\"><span class=\"ms-accessible\"></span>Dec<sp" +
                        "an class=\"ms-accessible\">2014</span></a></td>\r\n                                <" +
                        "/tr>\r\n                                <tr><td colspan=\"3\" class=\"ms-picker-foote" +
                        "r ms-textSmall\" dir=\"ltr\"><div>Today is <a href=\"#\" onclick=\"var ifrm = GetIfram" +
                        "e(); if (ifrm != null) ifrm.firstUp = true; MoveToDate(\'12\\u002f18\\u002f2014\'); " +
                        "return false;\">"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldivDate();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</a></div></td></tr></tbody></table>\r\n                            </div>\r\n       " +
                        "                 </div>\r\n                    </div>\r\n\t\t\t\t</div>\r\n               " +
                        " \r\n\t\t    </div>\r\n        \r\n</div>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
